from .about_view import AboutView
from .contact_view import ContactView
from .home_view import HomeView
from .profile_view import ProfileView
from .team_view import TeamView
from .dp_finance_view import DPFinanceView
from .dp_hritd_view import DPHritdView
from .dp_research_view import DPResearchView
from .dp_pmu_view import DPPmuView
from .dp_monitoring_view import DPMonitoringView
from .dp_lab_view import DPLabView