# Generated by Django 4.1 on 2022-10-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nimr_web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstaffprofile",
            name="staff_designation",
            field=models.CharField(default=None, max_length=120, verbose_name="Designation"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="staff_designation",
            field=models.CharField(default=None, max_length=120, verbose_name="Designation"),
            preserve_default=False,
        ),
    ]
