# Generated by Django 4.1 on 2022-10-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nimr_web", "0004_news_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpublication",
            name="publication_link",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Publications Link"
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="publication_link",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Publications Link"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpublication",
            name="publication_file",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="publication",
            name="publication_file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/publications"),
        ),
    ]
