# Generated by Django 4.1 on 2022-10-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nimr_web", "0005_historicalpublication_publication_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalnews",
            name="news_file_url",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="File URL"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="news_file_url",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="File URL"
            ),
        ),
    ]
