# Generated by Django 4.1 on 2022-12-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nimr_web", "0006_historicalnews_news_file_url_news_news_file_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstaffprofile",
            name="staff_name",
            field=models.CharField(max_length=130, verbose_name="Staff Name"),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="staff_name",
            field=models.CharField(max_length=130, verbose_name="Staff Name"),
        ),
    ]
