# Generated by Django 4.1 on 2022-12-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nimr_web", "0008_centremanagerphoto_historicalcentremanagerphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="centremanagerphoto",
            name="manager_photo_link",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Link to an Image"
            ),
        ),
        migrations.AddField(
            model_name="historicalcentremanagerphoto",
            name="manager_photo_link",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Link to an Image"
            ),
        ),
        migrations.AlterField(
            model_name="centremanagerphoto",
            name="centre_manager",
            field=models.FileField(
                blank=True, null=True, upload_to="nimr_web/static/assets/images/resource"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcentremanagerphoto",
            name="centre_manager",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
