# Generated by Django 4.1 on 2023-01-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nimr_web", "0008_remove_headdepartment_head_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="news_file",
            field=models.FileField(upload_to="uploads/news/"),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="staff_photo",
            field=models.FileField(upload_to="nimr_web/static/assets/images/team/"),
        ),
    ]
