# Generated by Django 4.1 on 2023-01-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nimr_web", "0009_alter_news_news_file_alter_staffprofile_staff_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="centremanagerphoto",
            name="manager_photo",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to="nimr_web/static/assets/images/resource/",
            ),
        ),
    ]
