# Generated by Django 4.1 on 2022-12-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nimr_web", "0011_headdepartment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="centremanagerphoto",
            name="centre_manager",
            field=models.FileField(
                blank=True, default=None, null=True, upload_to="assets/images/resource"
            ),
        ),
        migrations.AlterField(
            model_name="headdepartment",
            name="head_photo",
            field=models.FileField(upload_to="assets/images/team/"),
        ),
        migrations.AlterField(
            model_name="historicalcentremanagerphoto",
            name="centre_manager",
            field=models.TextField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="sliderphoto",
            name="slider_photo",
            field=models.FileField(blank=True, null=True, upload_to="assets/images/resource"),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="staff_photo",
            field=models.FileField(upload_to="assets/images/team/"),
        ),
    ]
