# Generated by Django 4.1 on 2022-12-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nimr_web", "0012_alter_centremanagerphoto_manager_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="centremanagerphoto",
            name="centre_manager",
            field=models.FileField(
                blank=True, default=None, null=True, upload_to="assets/images/resource/"
            ),
        ),
        migrations.AlterField(
            model_name="sliderphoto",
            name="slider_photo",
            field=models.FileField(blank=True, null=True, upload_to="assets/images/banner"),
        ),
    ]
